spring:
    main:
        banner-mode: off
        log-startup-info: false
    profiles:
        active: dev

server:
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

mybatis-plus:
    global-config:
        banner: false
